### ISSUE TITLE
Consult items on an interactive geographical map

### ISSUE THREAD

**Issue by aurorethomas** [Hypertopic/Porphyry#121]
## Content

Display selected items on a geographical map (depending on their `spatial` attribute) instead of as a list of names or thumbnails.

---

### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
### Phase 2
- [ ] Acceptance tests (Capybara)
- [x] Implementation

**Comment by RobinLallier** [comment]
Mock-ups attached : 

1. Map shows how many items are in a grouped locality
<img width="646" alt="Capture d’écran 2019-06-20 à 08 42 15" src="https://user-images.githubusercontent.com/33777989/59827179-482ef780-9338-11e9-80a3-7207e124db2c.png">

2. On zoom, clusters of items are split on more specific localities 
<img width="648" alt="Capture d’écran 2019-06-20 à 08 42 40" src="https://user-images.githubusercontent.com/33777989/59827240-6dbc0100-9338-11e9-9d77-482748ce6afe.png">
3. On Click on one of the localities, items present in this locality are showcased
<img width="645" alt="Capture d’écran 2019-06-20 à 08 43 04" src="https://user-images.githubusercontent.com/33777989/59827274-875d4880-9338-11e9-808b-b18e80049994.png">

**Comment by Ciyax** [comment]
Cette fonctionnalité semble intéressante dans le cadre du projet Studying abroad, elle permettrait de matérialiser et localiser sur une carte les différentes universités participantes au programme. Ainsi offrant la possibilité de s'y repérer rapidement et de trouver des lieux intéressants autour comme les possibilités de logement.

**Comment by Kodlah** [comment]
Projet Graines d'artistes : 
Fonctionnalité intéressante afin de visualiser les dessins des participants selon leur localisation géographique. Le but serait de pouvoir visualiser le nombre de dessins provenant d'un même endroit. Exemple : 326 dessins venant de France.

**Comment by benel** [comment]
Pensez à préciser si voir où sont vos items vous suffit ou si vous avez besoin de connaître la proportion d'items qui se trouvent ici ou là. Si c'est le cas, il est possible de faire deux livraisons (donc deux fonctionnalités) successives.

**Comment by sbramstein** [comment]
Greek vases : Cette fonctionnalité me semble être très importante pour voir la position des vases dans le cimetière. Toutefois au vu de la potentielle forte concentration de vases en un endroit, il faudrait définir une méthode de représentation avec potentiellement des couleurs et/ou des symboles et/ou autres de façon à ce que la représentation de la carte soit pertinente.

**Comment by benel** [comment]
@sbramstein Effectivement... Des réflexions aussi sur le fond de carte ?

**Comment by FirielEinor** [comment]
Visite sur site de vitraux :
Les vitraux étant réparti dans pleins d'endroit différent, avoir en visuel les différents endroit ayant des items

**Comment by melaniehoneychurch** [comment]
Pour le projet des vitraux cette fonctionnalité est particulièrement intéressante car on peut ainsi répertorier les vitraux selon les villages dans lesquels ils se trouvent. De plus si on couple avec le ticket #39 on pourra trouver sur la carte les églises et donc les vitraux dans cette église.

**Comment by benel** [comment]
> @sbramstein Greek vases : Cette fonctionnalité me semble être très importante pour voir la position des vases dans le cimetière. Toutefois au vu de la potentielle forte concentration de vases en un endroit, il faudrait définir une méthode de représentation avec potentiellement des couleurs et/ou des symboles et/ou autres de façon à ce que la représentation de la carte soit pertinente.

Je vous encourage à continuer de spécifier ce qui distinguerait votre carte de la carte standard des autres groupes. Prenez votre exemple précis du [Cimetière du Céramique](https://www.google.com/maps/@37.9784623,23.7169582,141m/data=!3m1!1e3).

Il est probable qu'une fois que ce sera fait, votre carte sera suffisamment différente pour être considérée comme une nouvelle fonctionnalité (améliorant celle décrite dans ce ticket) décrite dans un nouveau ticket.

**Comment by lefrancp** [comment]
Livrable effectué : 
![maquette 1](https://user-images.githubusercontent.com/43790227/81265100-c70d4b80-9042-11ea-8c0c-abffe4238bb9.PNG)
![maquette 2](https://user-images.githubusercontent.com/43790227/81265102-c7a5e200-9042-11ea-8e6a-ed178044c89e.PNG)

**Comment by benel** [comment]
@lefrancp Si je comprends bien : 

- dans la première étape, vous avez une sélection sur 2019, et ce que l'on voit sur la carte et dans la planche contact c'est ce qui correspond à cette première sélection,
- dans le deuxième étape, la carte et la planche contact ont été mis à jour pour correspondre à l'ajout du lieu (Russie) à la première sélection.

Si c'est le cas, le scénario sous-jacent est bien effectivement.

Par contre, ce qui m'a troublé c'est que la position des différentes parties existantes  (corpus et sélection par exemple sont inversés verticalement) et leur aspect sont vraiment très très différents. Du coup il est difficile de reconnaître les différentes zones.

À quoi sert le gros bouton "sélectionner" ? Faut-il cliquer dessus ?

**Comment by lefrancp** [comment]
Merci pour le retour, c'est effectivement le fonctionnement que nous imaginions. 
Nous allons effectuer les modification pour la position des éléments
Concernant le bouton "sélectionner", nous allons le retirer, on ne sait pas vraiment pourquoi on l'avait mis à la base..

**Comment by benel** [comment]
> Nous avons des questions notamment sur ce ticket , nous aimerions savoir si vous vous occupez juste de la réalisation de la maquette de la solution ou bien aussi de l’implémentation de cette dernière.

Pour ce ticket, j'intégrerai uniquement la version de base que vous avez prototypée lors de la dernière séance. Il s'agira donc uniquement d'une carte qui montre les lieux des items sélectionnés.

Si vous voulez un affichage du nombre d'items, une carte zoomable, des calques personnalisé, etc. Ce sera à vous d'améliorer cette carte.

C'est pour cela que c'est important que tous les groupes qui ont cette fonctionnalité dans leur kanban expliquent, dans la discussion de ce ticket, par des maquettes et des scénarios, de quoi ils ont besoin : 
- certains se satisferont de ma version simplifiée,
- d'autres auront besoin de créer un autre ticket (peut-être le même qu'un autre groupe, peut-être un différent).

**Comment by moonkeys** [comment]
La nouvelle version de la maquette simplifiée : 
![image](https://user-images.githubusercontent.com/43788230/81272754-32a8e600-904e-11ea-8041-e127c19654c6.png)

![image](https://user-images.githubusercontent.com/43788230/81273083-aba83d80-904e-11ea-8d9f-2249e5bbf86f.png)

**Comment by benel** [comment]
@moonkeys Effectivement, c'est bien plus compréhensible. 

Dernier petit point : pourquoi à la place du bouton d'ajout d'item, vous avez parfois un `+`(gris clair) et parfois un `-` (gris foncé) ?

**Comment by lefrancp** [comment]
C'était un problème de screenshot de la maquette, c'est mis à jour normalement maintenant

**Comment by benel** [comment]
>> Dernier petit point : pourquoi à la place du bouton d'ajout d'item, vous avez parfois un `+`(gris clair) et parfois un `-` (gris foncé) ?

> C'était un problème de screenshot de la maquette, c'est mis à jour normalement maintenant

Je vois toujours ceci : 
<img width="283" alt="Capture d’écran 2020-05-07 à 10 18 19" src="https://user-images.githubusercontent.com/597307/81271223-215eda00-904c-11ea-9fe0-bf27483c50aa.png">

**Comment by lefrancp** [comment]
Ah oui pardon, on a confondu avec une autre fonctionnalité, on corrige ça

**Comment by lefrancp** [comment]
C'est corrigé

**Comment by Kodlah** [comment]
Pour l'équipe Graine d'artistes : 

- Le binôme @moonkeys et @lefrancp s'occuperont du livrable Scénario pour ce ticket (#121).

- Le binôme @macchrd et @neumeiej s'occuperont de la Stratégie d'Implémentation de ce ticket (#121).

**Comment by SorelMboua** [comment]
1. L'utilisateur consulte les différents sites sur la carte du monde

![Issue 121 - 1](https://user-images.githubusercontent.com/54583293/81276845-db0d7900-9053-11ea-97a4-48049f87bf90.png)

2. Puis il sélectionne un site, par exemple "Sanctuaire de l’Olympe". Il est redirigé vers une page avec la carte du site et la localisation des différents vases.

![Issue 121 - 2](https://user-images.githubusercontent.com/54583293/81276961-04c6a000-9054-11ea-9b6e-4cf3a0bff4c5.png)

3. L'utilisateur peut cliquer sur l'une des images à gauche pour avoir des informations plus précises sur l'item. Il sera donc redirigé vers la page de l'item

**Comment by benel** [comment]
@SorelMboua C'est joli... mais essayez si possible de garder la structure de l'application existante. Autrement dit montrez les deux mêmes cartes mais à l'intérieur de la page du portfolio (donc en gardant et éventuellement en réutilisant toutes les fonctionnalités existantes de cette page).

**Comment by SorelMboua** [comment]
![Issue 121 - 1 v1](https://user-images.githubusercontent.com/54583293/81279513-8bc94780-9057-11ea-9a0c-93ca9f7adf5a.png)


![Issue 121 - 2 v2](https://user-images.githubusercontent.com/54583293/81279531-91269200-9057-11ea-8649-9edfc2944940.png)

**Comment by benel** [comment]
@SorelMboua C'est mieux. Cependant quelques problèmes encore : 

- [ ] Maquette n°1
    - [ ] Il n'y a pas de bouton "retour" dans la page du portfolio.
  - [ ] Les partes que vous n'avez pas fait figurer me semblent pourtant nécessaires à la compréhension de ce que l'on voit : 
    - [ ] Quel est le corpus ? Autrement dit, qu'est-ce qui est localisé sur la carte ?
    - [ ] Quelle est la sélection ? Et du coup, peut-on la changer et voir changer la carte ?
- [ ] Maquette n°2
    - [ ] Il n'y a pas de bouton "retour" dans la page du portfolio.
  - [ ] Si je ne me trompe pas c'est la carte du sanctuaire d'Olympie. À moins que ce soit M. Luce qui vous ait demandé de changer d'exemple, on était plutôt partie sur une nécropole (celle du Céramique à Athènes) plutôt que sur un sanctuaire... Ce n'est pas qu'un détail, parce que par exemple ça veut dire que pour un même lieu (ex : tombe n°4), vous allez avoir plusieurs vases.
  - [ ] OK pour la sélection sanctuaire d'Olympie, c'est le thème de la page, mais du coup, on va éviter de parler de choses différentes sur la même page (Londres 1912...). Si vous voulez faire une autre sélection, c'est juste un nouveau critère et donc une troisième maquette qui montre une nouvelle étape.
   - [ ] Si vous voulez être cohérent entre les deux maquettes (puisque c'est la même fonctionnalité), soit vous sélectionnez une position, soit une catégorie, soit un attribut. Vouloir tout faire est extrêmement ambitieux...

**Comment by moonkeys** [comment]
**Fonctionnalité**: Consulter des éléments sur une carte géographique

**Contexte**:

Soit "dessins" le portfolio ouvert & qu'on est sur la carte

**Scénario**: Recherche par attribut Spatial

Quand on ajoute un attribut de recherche "Spatial" avec pour valeur "Russie"
Alors le dessin "1996_14-17_13_RUS_R_C " & "2015_6-9_18_RUS_R_C" est affiché et le marqueur correspondant au pays sélectionné passe de rouge à vert et dans le marqueur le nombre 2 est affiché


**Scénario**: Recherche par attributs Spatial et Created

Quand on ajoute un attribut de recherche "Created" avec pour valeur "2013" et un attribut de recherche "Spatial" avec pour valeur "Cameroun"
Alors les dessins "2013_18-25_10_CMR_R_A" est affiché et le marqueur correspondant au pays sélectionné passe de rouge à vert et dans le marqueur le nombre 1 est affiché

**Comment by macchrd** [comment]
**Stratégie d'implémentation :** 

La carte sera un composant à part entière.
Il faudra pouvoir accèder depuis ce composant aux éléments du corpus, et plus particulièrement à leurs attributs "spatial".
Sachant que ce composant sera intégré au sein du composant portfolio, les éléments du corpus pourront-être facilement passés en props du composant map. 

Nous utiliserons le service google maps pour pouvoir générer des images de cartes.
La carte sera agrémentée de marqueurs positionnés sur chaque pays possédant des éléments du corpus.
Ces marqueurs seront cliquables et permettront d'effectuer du filtrage sur les éléments du corpus.

Pour pousser encore le développement de cette fonctionnalité, nous pourrions utiliser la bibliothèque google-map-react ( lien : _https://www.npmjs.com/package/google-map-react_)

Cette bibliothèque permet notamment de passer n'importe quel composant react en tant que marqueur et d'avoir une carte navigable.

Il y a aussi un exemple de "clustering" qui pourrait être utilisé pour rendre la carte encore plus interactive. (lien : _https://github.com/leighhalliday/google-maps-clustering_)

**Comment by benel** [comment]
@macchrd OK mais chez Google, il y a [plusieurs API](https://developers.google.com/maps/documentation?hl=fr)... 

Il faudrait en particulier définir si vous pouvez vous satisfaire de la version dite statique (sous forme d'image) qui a été implémentée en cours et qui sera intégrée sous peu ou si vous avez absolument besoin de la version interactive.

**Comment by macchrd** [comment]
Nous pensons que la version interactive sera obligatoire pour l'implémentation de cette fonctionnalité telle que nous l'avons pensée. En effet, je ne pense pas qu'il soit possible d'effectuer des "clicks" sur la carte statique développée en cours. L'api qui devra être utilisée est donc Google Maps JavaScript API, celle utilisée par la bibliothèque mentionnée dans mon précédent message.

 Néanmoins, nous nous demandons si nous n'avons pas amené trop loin cette fonctionnalité (peut-être au dessus de nos capacités techniques actuelles sur React ?) qui n'est à la base que de la consultation.  Pensez-vous que nous devrions revoir nos maquettes dans l'optique d'utiliser une carte statique ou continuer sur l'idée d'avoir une carte interactive ? @benel

**Comment by benel** [comment]
> Néanmoins, nous nous demandons si nous n'avons pas amené trop loin cette fonctionnalité (peut-être au dessus de nos capacités techniques actuelles sur React ?) qui n'est à la base que de la consultation. Pensez-vous que nous devrions revoir nos maquettes dans l'optique d'utiliser une carte statique ou continuer sur l'idée d'avoir une carte interactive ?

Vous ne pouviez pas me faire plus plaisir. Ce que vous pointez du doigt, là, c'est la clef d'un projet agile réussi. 

J'ai envie de vous répondre : "Tout dépend des **besoins** de vos parties prenantes", ou pour être plus précis **de leurs priorités**. En effet si vous leur donniez le choix entre les deux, ils voudraient probablement ce qu'il y a de mieux. Mais la vraie question est que le temps que vous passerez à faire la version améliorée, vous ne ferez pas une autre fonctionnalité qui pourtant était plus importante.

Si vous êtes tous d'accord dans votre équipe (Graines d'artistes), voici comment faire : 

- Créez une nouveau ticket au nom similaire mais plus précis du genre `Consult items on a static geographical map`. Et dans votre kanban, intervertissez le avec le ticket actuel (qui passe du coup tout en bas de suggested).
- Dès la livraison de la carte statique, vous aurez un nouveau livrable !!!
- Si une autre équipe implémente la version dynamique, ce sera "tout bénef" pour vous, et ce sera à eux de vérifier qu'ils n'ont pas cassé ce que l'on pouvait faire avec la carte statique (d'où l'importance que votre test automatisé ait été intégré, je vous aiderai pour le critère de validation car, comme c'est visuel et non textuel, il faudra ruser).

**Comment by benel** [comment]
Deployed.

**Comment by benel** [comment]
@florian-dehe 

> En travaillant sur le scénario du ticket #349 , nous avons remarqué que dans la version que l'on "clone" depuis Github ne contient pas la fonctionnalité de la carte (contrairement à vitraux.porphyry.org)

En fait si, mais il faut indiquer votre clef d'API GoogleMap dans le fichier de configuration (`conf.yml`) en tant que `interactiveMap`. 

> De plus, il n'y a pas de scénarios (ou de fichier .feature) associé à cette fonctionnalité.

C'est exact. Deux raisons à cela : 
- pour éviter de diffuser publiquement la clef d'API (même s'il est possible de la passer à Google Actions par une variable d'environnement), 
- par ce qu'il est assez difficile de tester visuellement la carte avec Capybara (mais on pourrait par exemple tester l'URI d'appel de la carte).
