### ISSUE TITLE
Assign a topic to every selected item

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#159]
#### For which stakeholder (people, role, project, domain) is it important?

As reported by @gumn, this could be useful for the Cité du vitrail especially for items with the same name (requires #158).

#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Mockups
- [ ] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

### Phase 3
- [ ] Screencast

**Comment by TomikaArome** [comment]
### Mockups

![Actuel](https://user-images.githubusercontent.com/26234396/57836640-73667a00-77c1-11e9-868b-ce3585878345.png)
![Selection](https://user-images.githubusercontent.com/26234396/57836660-7fead280-77c1-11e9-8b80-f6fd936e542c.png)
![Modifier](https://user-images.githubusercontent.com/26234396/57836668-85481d00-77c1-11e9-8722-c4fff6372fee.png)
![Attribuer Topic](https://user-images.githubusercontent.com/26234396/57836686-8b3dfe00-77c1-11e9-9e1b-a803807c65b0.png)

**Comment by pstacho** [comment]
### Maquette V2 : 
[assign_topic_to_every_selected_item.pdf](https://github.com/Hypertopic/Porphyry/files/3243590/assign_topic_to_every_selected_item.pdf)

J'ai simplifié la sélection du topic à attribuer pour que l'interface ne soit pas trop lourde comme on en avait discuter la fois précédente. Qu'est-ce que vous en pensez ?

**Comment by pstacho** [comment]
**Spécifications du scénario** 

- [x] Est-il bien rédigé pour les usagers et non pour l'équipe de développement ?

- [x] Décrit-il bien un cas précis et réaliste ?

- [x] Est-il "minimal" pour expliquer la fonctionnalité ou est-ce que certaines étapes ou données pourraient être supprimées ?

- [x] Reste-t-il valable même si l'interface change mais que la fonctionnalité demeure ?

- [x] Les conditions du scénario restent-elles valables si on suit le scénario plusieurs fois ? si on suit d'autres scénarios ?

- [x] Les conditions du scénario restent-elles valables si on ajoute des données sur le serveur ?

- [x] La fonctionnalité du scénario correspond-t-elle à une fonctionnalité "officielle" du logiciel ?

**Comment by benel** [comment]
Attention de ne pas fermer la fonctionnalité tant qu'elle n'est pas intégrée dans la branche principale (`V7`). Vous pouvez garder le ticket simultanément ouvert et en "Done". Ensuite, le message de commit contenant `closes #159` fermera automatiquement le ticket quand il sera intégré à la branche principale.

**Comment by bheroult** [comment]
Pour le projet des vases : permettrait de fournir des éléments de description et classer les items rapidement depuis la recherche dans le portfolio

**Comment by EmileReyUL** [comment]
Approche par compétences de la formation : Permettrait d'assigner un topic (exemple : CS) à un groupe d'UEs sélectionnées d'un seul coup.

**Comment by seguragu** [comment]
Pour le projet Stained glasses "on site". Permet d'ajouter un élément supplémentaire pour organiser les items (vitraux) dans son portfolio.

Par exemple le topic "Toussaint" pour sélectionner tous les vitraux que l'utilisateur souhaite aller visiter pendant ses vacances de la Toussaint.

**Comment by benel** [comment]
@seguragu On est d'accord qu'il s'agit ici de **créer de nouvelles données** à partir de données existantes ?

**Comment by franckfotso1** [comment]
Pour le projet Kerameikos, cette fonctionnalité permettrait aux utilisateurs de donner plus d'éléments caractéristiques sur la description d'un item (vase...) afin de mieux les catégoriser et élargir le champ de recherche.

**Comment by benel** [comment]
@franckfotso1 @Hypertopic/kerameikos 

> de donner plus d'éléments caractéristiques sur la description d'un item

Dans le cas précis de cette fonctionnalité, il s'agit plus précisément de _plus_ d'items _par_ élément caractéristique. Mais je vois ce que vous voulez dire : effectivement, on peut espérer l'effet dont vous parlez.
