### ISSUE TITLE
Reset one's password

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#185]
### Description

Requires that an e-mail is linked to the account (see #184).

#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Mockups
- [ ] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

### Phase 3
- [ ] Screencast

**Comment by garnier5** [comment]
For the "studying abroad" project, you need to enable to password's changes so that the users of the platform can be autonomous

**Comment by benel** [comment]
@garnier5 What are your reasons for not using LDAP authentication from the sending institution?  Or are there external users?

**Comment by hebertquentin** [comment]
Il serait utile en Archéologie grecque de pouvoir réinitialiser un mot de passe. La plateforme web ne montre pas réellement si cela est déjà implémenté.

**Comment by garnier5** [comment]
@benel Indeed, if we can use the sending institution's LDAP, we can remove the account creation and password modification features.

**Comment by Gaetanherry** [comment]
Dans le partage d'expériences cela peut être utile pour avoir des utilisateurs autonomes

**Comment by ValentinLouerat** [comment]
Projet : Approche par compétence de la formation
Les utilisateurs auront plus de contrôle sur leur compte

**Comment by benel** [comment]
@ValentinLouerat La plupart des participants de votre plateforme ne sont ils pas à l'UTT ?  Dans ce cas ils ont déjà des comptes dans le LDAP institutionnel... Avez-vous des raisons de ne pas l'utiliser ?

**Comment by ElizabethBricoutUTT** [comment]
**Scénarios**

Scénario: apparition du formulaire de réintialisation du mot de passe
Soit la page d'accueil
Quand l'utilisateur clique sur le bouton pour réinitialiser son mot de passe
Alors le formulaire de réinitialisation du mot de passe s'affiche.

Scénario: reset du mot de passe
Soit le formulaire de réinitialisation du mot de passe.
Quand l'utilisateur rempli le champ nom d'utilisateur avec "alice"
Et valide
Alors un email pour reset le mot de passe est envoyé à l'adresse mail lié "alice.whiterabbit@gmail.com"

Scénario: création nouveau mot de passe
Soit la page de création de nouveau mot de passe
Quand l'utilisateur entre le mot de passe "1234" dans le champ de nouveau mot de passe
Et l'utilisateur entre le mot de passe "1234" dans le champ de vérification de nouveau mot de passe
Et valide
Alors le nouveau mot de passe "1234" est lié au compte "alice"

**Comment by wikolas21** [comment]
> **Scénarios**
> 
> Scénario: reset du mot de passe
> Soit la page accueil
> Et l'utilisateur clique sur le bouton "Mot de passe oublié"
> Quand le formulaire de récupération de mot de passe apparaît
> Quand la valeur de l'attribut "nom d'utilisateur" est remplie
> Et le bouton "envoyer mail de récupération" est cliqué
> Alors un email pour reset le mot de passe est envoyé à l'adresse mail lié au nom d'utilisateur
> 
> Scénario: création nouveau mot de passe
> Soit un email pour reset le mot de passe est envoyé à une adresse email
> Et l'utilisateur l'ouvre
> Quand le formulaire de création d'un nouveau mot de passe apparaît
> Quand l'attribut "nouveau mot de passe" est remplie
> Et l'attribut "vérification nouveau mot de passe" est remplie
> Et le bouton "valider" est cliqué
> Alors le nouveau mot de passe est associé au compte

La maquette associée : https://xd.adobe.com/view/e5f62fa2-b666-40bf-4e33-305239920793-93c7/?fullscreen&hints=off

**Comment by benel** [comment]
@ElizabethBricoutUTT 

> Et l'utilisateur clique sur le bouton "Mot de passe oublié"

Normalement, si je ne regarde dans votre scénario que ce qui est entre guillemets, je dois retrouver tous les **détails** (les données, les exemples) de mon histoire (le portfolio auquel je voulais me connecter, mon nom de connexion, mon adresse électronique, etc.). Là vous voyez au contraire que c'est un élément de l'interface. C'est parce que les phrases sont trop orientées autour de l'IHM. Essayez de monter en abstraction.

> Quand le formulaire de création d'un nouveau mot de passe apparaît

Le `Quand` doit correspond à une action de l'utilisateur.

> Quand l'attribut "nouveau mot de passe" est remplie

Dans un scénario Gherkin, il ne peut y avoir qu'un seul `Quand`.

> Et l'attribut "vérification nouveau mot de passe" est remplie
> Et le bouton "valider" est cliqué

Les `Alors` sont des conditions sur les résultat, pas des actions de l'utilisateur.

Notez encore qu'en montant en abstraction, vous allez pouvoir justement englober plein d'actions élémentaires en une seule action (qui normalement correspond à votre fonctionnalité).

**Comment by benel** [comment]
@wikolas21 

Merci pour cette maquette. Quelques pistes d'amélioration : 

- [ ] attention à la cohérence de l'interface, si vous regardez bien dans Porphyry, il y a nulle part de "dialogues" ou de fenêtres modales,
- [ ] attention, à l'orthographe et à la formulation, cela fait partie de l'interface,
- [ ] si je recevais un courriel comme ça, moi, je ne cliquerais jamais sur le lien ;) Réfléchissez bien à tout ce qui doit apparaître dans le courriel pour que le destinataire puisse cliquer sans prendre un risque inconsidéré.

**Comment by ElizabethBricoutUTT** [comment]
@benel J'ai ajouté un nouveau scénario et modifié pour monter en abstraction comme vous aviez conseillé, est ce mieux?
