### ISSUE TITLE
Duplicate a portfolio to customize it

### ISSUE THREAD

**Issue by pstacho** [Hypertopic/Porphyry#190]
### Description
related to #189 

Create a copy of the selected portfolio for a private use. The modification made on it will not impact the original portfolio.

#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Mockups
- [ ] Implementation strategy
#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation
#### Phase 3
- [ ] Screencast

**Comment by RobinLallier** [comment]
[duplicate_portfolio.pdf](https://github.com/Hypertopic/Porphyry/files/3185960/duplicate_portfolio.pdf)

**Comment by RobinLallier** [comment]
Page portfolio
![Page principal](https://user-images.githubusercontent.com/33777989/57836566-3f8b5480-77c1-11e9-8c34-03b68b6068ac.png)
Pop-Up
![Pop-up dupplication](https://user-images.githubusercontent.com/33777989/57836567-4023eb00-77c1-11e9-83af-3bbb28fae1a5.png)
Confirmation
![confirmation](https://user-images.githubusercontent.com/33777989/57836562-3f8b5480-77c1-11e9-9c08-f2fbe24170c3.png)
Nouveau portfolio
![new portfolio](https://user-images.githubusercontent.com/33777989/57836563-3f8b5480-77c1-11e9-9452-e097018c4e2f.png)

**Comment by AxelRagobert** [comment]
Lien vers mon fork : https://github.com/AxelRagobert/Porphyry.git

**Comment by RobinLallier** [comment]
## TODO Développement

### Front
- [x] Créer un bouton "Dupliquer" dans le Header, ce bouton contrôle l'ouverture du modal (Thai et Phuc )

- [x] Créer un composant Modal de paramétrage de la copie (Robin et Axel)

- [x] Créer un composant Modal de confirmation (Robin et Axel)

- [x] (Optionnel) : ajouter un toaster "la duplication a réussie. Vous allez être redirigé dans quelques instants.." (Thai et Phuc ) [https://react-bootstrap.netlify.com/components/toasts/](url)

### Back 

- [x] Générer une référence vers le nouveau Portfolio (ex: créer référence portfolio "VitrauxARCHE")

- [x] Référencer les points de vue sélectionnés vers le portfolio créé

- [x] Référencer les corpus sélectionnés vers le portfolio créé

- [x] Renvoyer un message "réussite" vers le Front

**Comment by RobinLallier** [comment]
Spécifications des scénarios 

- [x] Est-il bien rédigé pour les usagers et non pour l'équipe de développement ?

- [x] Décrit-il bien un cas précis et réaliste ?

- [x] Est-il "minimal" pour expliquer la fonctionnalité ou est-ce que certaines étapes ou données pourraient être supprimées ?
--> Vérifié

- [x] Reste-t-il valable même si l'interface change mais que la fonctionnalité demeure ?

- [x] Les conditions du scénario restent-elles valables si on suit le scénario plusieurs fois ? si on suit d'autres scénarios ?
--> Fonctionne

- [x] Les conditions du scénario restent-elles valables si on ajoute des données sur le serveur ?

- [x] La fonctionnalité du scénario correspond-t-elle à une fonctionnalité "officielle" du logiciel ?

**IMPORTANT : Le test nécessite une configuration particulière de plusieurs fichiers, notamment etc/hosts, et ne fonctionne donc pas sous Travis CLI**

**Comment by cedfre** [comment]
@Hypertopic/competences-eut 

Cette fonctionnalité permettrait par exemple aux professeurs de dupliquer un portfolio d'items existant (donc un portfolio d'UV existant ) afin de gagner du temps dans la création d'un nouveau portfolio d'UV avant publication.

**Comment by benel** [comment]
@cedfre @Hypertopic/competences-eut  C'est peut-être intéressant pour votre cas, mais l'usage que vous en feriez est encore un peu flou.

Dupliquer un portfolio, permet de créer un nouveau site avec dans un premier temps les mêmes corpus d'items et les mêmes points de vue (c'est une inclusion par référence si on les modifie là ils seront modifiés également dans le portfolio d'origine). Ensuite, on peut retirer certains corpus et points de vue et en ajouter d'autres.
