### ISSUE TITLE
Complex boolean query with "and", "or" and "not" should have the right result

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#366]
# Rationale

This bug was unnoticed for 2 years, but I experienced it when I used the feature to find which stain glasses were still not described.

# Reproduction scenario

On vitraux.porphyry.org:
Let `A` be `datation`.
Let `B` be `personnages`.
Let `C` be `récit`.

Input | Current output | Desired output
------|----------------|---------------
`not(A) or (not(B) or not(C)) ` | 1303 items | It should be the largest set!
`not(A) or (not(B) and not(C)) ` | 1467 items |
`not(A) and (not(B) or not(C)) ` | 773 items |
`not(A) and (not(B) and not(C)) ` | 1031 items | It should be the smallest set!

# Deliverables status

## Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Mockups
- [ ] Implementation strategy
## Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

**Comment by alca-creator** [comment]
Parmi les fonctionnalités proposées par le logiciel Phorphyry, la fonctionnalité "**Consulter les items correspondant à des conjonctions (ET), disjonctions (OU) ou même absences (NON) de catégories**" nous semblait pertinente pour le projet **Kerameikos**. Elle se révèle utile pour préciser ses recherches (localisation précise, époque, matériaux, ...). Il est donc important que la requête booléenne affiche le bon résultat.

**Comment by benel** [comment]
> la fonctionnalité "Consulter les items correspondant à des conjonctions (ET), disjonctions (OU) ou même absences (NON) de catégories" nous semblait pertinente pour le projet Kerameikos

Oui, effectivement elle plaît beaucoup à M. Luce.

> Il est donc important que la requête booléenne affiche le bon résultat.

C'est vrai... Mais petit bémol cependant : nous n'avons constaté le bug que deux ans après la mise en service de la fonctionnalité. La fonctionnalité a pourtant été utilisée dans des cas très complexes (cf. le cas de l'"art déco" dans les vidéos de démonstration). Le bug apparaît dans un cas très particulier (et pas encore très très bien isolé) relatif à la combinaison d'une requête négative et d'un autre opérateur (nous ne savons pas encore lequel).

**Comment by benel** [comment]
> Le bug apparaît dans un cas très particulier (et pas encore très très bien isolé) relatif à la combinaison d'une requête négative et d'un autre opérateur (nous ne savons pas encore lequel).

Le dysfonctionnement est désormais beaucoup mieux isolé.
Dans le cas du [jeu de test](https://github.com/Hypertopic/Argos/tree/v4/__tests__/api/fixtures) officiel d'Argos et de Porphyry, voici les résultats théoriques des requêtes composées à partir des deux rubriques "Artiste" et "Datation" : 


AND | `Artiste` | `not(Artiste)`
---|---|---
**`Datation`** | SM 001 n | AXN 009 (noir et blanc), SM001 m, SM 008 g, SNZ 006, SR 005
**`not(Datation)`** | | AXN 009 (couleur), PSM 002, SJ 001, SNZ 005 (baie), SNZ 009

Autrement dit, voici les résultats attendus pour les requêtes suivantes  : 

Requête | Réponse attendue
---------|------------------
`not(Datation) AND not(Artiste)` | AXN 009 (couleur), PSM 002, SJ 001, SNZ 005 (baie), SNZ 009
`not(Datation) OR not(Artiste)` | AXN 009 (les deux), PSM 002, SJ 001, SM001 m, SM 008 g, SNZ 005 (baie), SNZ 006, SNZ 009, SR 005

**Comment by benel** [comment]
# Stratégie d'implémentation

## Quelle partie du code sera impactée (classes, méthodes) ?

En première approche, on peut se baser sur le code des deux fonctionnalités impactées (073c209, e1388f7).
Au moment de l'implémentation des ces fonctionnalités, leur code était situé dans les classes suivantes : 

- [portfolioPage/Portfolio](https://github.com/Hypertopic/Porphyry/blob/v7/src/components/portfolioPage/Portfolio.jsx) et plus particulièrement dans les méthodes : 
  - render,
  - isSelectedItem,
  - _updateSelectedItems,
  -   _getViewpoints,
  - includes ;
- [portfolioPage.Topic](https://github.com/Hypertopic/Porphyry/blob/v7/src/components/portfolioPage/Topic.jsx)  et plus particulièrement dans les méthodes : 
  - render,
  - _getSubtopics,
  - handleClick,
  - updateSelectionJSON,
  - switchPlace ;
- [portfolioPage.Viewpoint](https://github.com/Hypertopic/Porphyry/blob/v7/src/components/portfolioPage/Viewpoint.jsx)  et plus particulièrement dans la méthode : 
  - _getTopics ;
- [portfolioPage.Status](https://github.com/Hypertopic/Porphyry/blob/v7/src/components/portfolioPage/Status.jsx) ;
- [portfolioPage.Badge](https://github.com/Hypertopic/Porphyry/blob/v7/src/components/portfolioPage/Badge.jsx) ;
- [portfolioPage.Button](https://github.com/Hypertopic/Porphyry/blob/v7/src/components/portfolioPage/Button.jsx).

Comme on le voit, le nombre de lignes relatives à ces fonctionnalités est très élevé (d'autant plus que d'autres fonctionnalités en lien avec celles-ci ont été implémentées depuis, comme par exemple la recherche).

Une autre approche est de se focaliser la gestion de la "sélection" et plus particulièrement de la structure de donnée `selectionJSON`, choisie par celles et ceux qui avaient implémenté les fonctionnalités. La liste des [lignes mentionnant `selection`](https://github.com/Hypertopic/Porphyry/search?q=selection) permet de désigner à la fois des parties plus précises du code et de manière plus exhaustive (car correspondant au code actuel avec toutes ses nouvelles fonctionnalités) : 

https://github.com/Hypertopic/Porphyry/blob/96cf84ffd58a3a365de663e9f7e63f9e62a2ff14/src/components/portfolioPage/Status.jsx#L9
https://github.com/Hypertopic/Porphyry/blob/96cf84ffd58a3a365de663e9f7e63f9e62a2ff14/src/components/portfolioPage/Status.jsx#L14
https://github.com/Hypertopic/Porphyry/blob/a24c55f578324595888888ad4c4117a654960592/src/components/portfolioPage/Topic.jsx#L18-L19
https://github.com/Hypertopic/Porphyry/blob/a24c55f578324595888888ad4c4117a654960592/src/components/portfolioPage/Topic.jsx#L42-L43
https://github.com/Hypertopic/Porphyry/blob/5e3c85a79a3831e36a56f13baafd5c18327afe98/src/components/portfolioPage/Portfolio.jsx#L44
https://github.com/Hypertopic/Porphyry/blob/5e3c85a79a3831e36a56f13baafd5c18327afe98/src/components/portfolioPage/Portfolio.jsx#L111-L129
https://github.com/Hypertopic/Porphyry/blob/96cf84ffd58a3a365de663e9f7e63f9e62a2ff14/features/step_definitions/context.rb#L17-L27
https://github.com/Hypertopic/Porphyry/blob/a24c55f578324595888888ad4c4117a654960592/src/components/portfolioPage/Viewpoint.jsx#L29-L32
https://github.com/Hypertopic/Porphyry/blob/a24c55f578324595888888ad4c4117a654960592/src/components/portfolioPage/SearchBar.jsx#L42-L49
https://github.com/Hypertopic/Porphyry/blob/5e3c85a79a3831e36a56f13baafd5c18327afe98/src/components/itemPage/TopicPath.jsx#L63
https://github.com/Hypertopic/Porphyry/blob/5e3c85a79a3831e36a56f13baafd5c18327afe98/src/components/portfolioPage/GeographicMap.jsx#L70
https://github.com/Hypertopic/Porphyry/blob/a24c55f578324595888888ad4c4117a654960592/src/components/itemPage/Attribute.jsx#L103

## Y aura-t-il des difficultés d'un point de vue algorithmique ? Avez-vous des pistes pour les résoudre ?

L'algorithme présentant le dysfonctionnement est assimilable à une classe de problèmes bien connus en informatique : l'analyse syntaxique et sémantique d'un langage formel (ici : une expression booléenne correspondant à ce que cherche l'utilisateur).
Le problème étant réputé difficile et les concepteurs de l'époque (étudiants d'il y a deux ans) ne faisant plus partie de l'équipe, il semble hasardeux de localiser plus précisément l'origine du dysfonctionnement et de le corriger. En effet, rien ne nous assurerait que d'autres dysfonctionnements dans d'autres cas, encore non explorés, soient découverts par la suite.
Par ailleurs, les choix de conception de l'époque ont pour conséquence que les URI sont extrêmement longues et sont également difficiles à générer (notamment pour les tests).  Une demande de réusinage à ce propos (#207) a d'ailleurs été déposée.
Pour toutes ces raisons, nous choisissons de changer le code _adhoc_ par un analyseur syntaxique et sémantique d'expressions booléennes développé, testé et maintenu par un tiers.

## Les données dont vous avez besoin sont-elles déjà chargées par la page ? Si oui, quelle est la structure des données et comment allez-vous récupérer précisément celles qui vous intéressent ?  Si non, quelle sera la requête la plus efficace  et comment allez-vous récupérer dans la structure de données précisément celles qui vous intéressent ?

Pour afficher la requête sous une forme compréhensible par l'utilisateur, il faut remplacer l'identifiant des thèmes par leur nom. Pour cela, les données sont déjà disponibles dans le ortfolio en tant que `this.state.viewpoints` avec la structure `[viewpoint].[topic].name`.

Pour utiliser la requête comme filtre des items, il faut soit développer la requête (en ajoutant toutes les rubriques spécifiques des rubriques mentionnées) soit développer les item (en ajoutant toutes les rubriques génériques des rubriques mentionnées). Dans les deux cas, il faut avoir accès à la structure du point de vue, qui est également disponible dans le portfolio en tant que `this.state.viewpoints` avec la structure `[viewpoint].[topic].broader` ou `[viewpoint].[topic].narrower` (à faire de manière récursive).

## Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ?

Comme nous le disions plus haut, nous avons choisir de remplacer le code sur mesure par un analyseur syntaxique et sémantique d'expressions booléennes développé, testé et maintenu par un tiers. Sur npmjs.com, nous avons présélectionné : 
- [ExpressionParser](https://www.npmjs.com/package/expressionparser), analyseur générique, nécessitant de définir l'effet des opérateurs booléens, pour obtenir un évaluateur,
- [BooleanParser](https://www.npmjs.com/package/boolean-parser), analyseur d'expressions booléens (sous forme de listes de listes correspondant à des disjonctions de conjonctions, avec une méthode de normalisation/simplification), gérant les parenthèses mais pas les négations, 
- [Voll](https://www.npmjs.com/package/voll), analyseur d'expression booléenne, qui fournit une fonction d'évaluation à appliquer à une chaîne de caractère représentant ce qui est connu comme vrai,
- [Boon-JS](https://www.npmjs.com/package/boon-js), analyseur d'expression booléenne, qui fournit une fonction d'évaluation à appliquer à un objet pour lequel chaque clef associée à un booléen correspond à un des termes dont on connaît la valeur (`undefined` et `false` sont équivalents).

En résumé : 
- Pour le filtrage d'items, Voll et Boon-JS semblent les plus adaptés (à condition de pouvoir transformer la description des items sous une forme compatible). 
- Pour des opérations sur les expressions elle-mêmes (ajout/modification/suppression de critères, expansion de requête), ExpressionParser semble le seul utilisable pour convertir l'expression en une structure manipulable.

## Comme dans notre séance sur le développement, vous pouvez tester des petits bouts de code indépendants et les associer à votre stratégie (avec éventuellement des exemples de données, voire même des temps d'exécution).

Cas de test : Est-il question de `"Bond OU 007"` dans un film qui parle de `["007", "Moneypenny"]` ?

- Avec Voll

```js
let parse = require("voll")
let test = parse('Bond OR 007')
test(['007','Moneypenny'])
```

- Avec Boon-JS

```js
let { getEvaluator } = require("boon-js")
let test = getEvaluator('Bond OR 007')
test(['007','Moneypenny'].reduce((m, v) => (m[v] = true, m), {}))
```

Le fait que la conversion d'un tableau en chaîne de caractère soit implicite, simplifie beaucoup l'utilisation de Voll par rapport à Boon-JS.

## Doit-on intégrer des services extérieurs (ex : cartographie) ? De quelles fonctionnalités en particulier aura-t-on besoin ? Est-ce que le service choisi les propose ou doit-on passer chez un concurrent ? Comment s'utilisent ces fonctionnalités ? avec quels paramètres ?

Ne s'applique pas.

## Des étapes préalables de développement, testables, sont-elles envisageables afin de diminuer la complexité de la livraison ? Refactoring (livrable à part entière, isofonctionnel) ? Code développable et testable de manière externe au logiciel ? Étape du scénario (non livrable en tant que tel mais dont l"effet peut être testé) ?

Dans l'absolu il serait idéal de passer la fonction fournie par l'analyseur à la fonction `filter` du tableau des items. Mais, sauf erreur de notre part, cela nécessiterait un refactoring complexe de l'algorithme au cœur de Porphyry (#213).

Il est peut-être possible d'implémenter et de tester le parsing d'URI avant de gérer les modifications interactives de la sélection. 
De même, il est sûrement souhaitable de faire le refactoring de l'affichage de la sélection avant de faire le refactoring du filtrage des items (le premier facilitera le debugging du second).
Attention aucune de ces étapes n'est hélas livrable indépendamment (le logiciel sera non fonctionnel tant que les 4 ne seront pas implémentées). 

Cependant, il serait possible de développer une classe (testable indépendamment de Porphyry) pour gérer les différents aspects de la Sélection (parsing de l'URI, sérialisation pour l'usager, modification d'un critère...).

Notons enfin que le refactoring du parsing et de la sérialisation de l'URI #207 (mais en conservant dans un premier temps la structure JSON existante), pourrait constituer une première étape... Par ailleurs, un premier refactoring pourrait consister à regrouper toutes les actions relatives à selectionJSON dans la même classe. Ainsi, ce serait beaucoup plus facile par la suite de changer son implémentation.

**Comment by benel** [comment]
Avancée des développements : 

- [x] Refactoring de selectionJSON sous forme d'une classe
  - [x] Porphyry/src/components/portfolioPage/Status.jsx
  - [x] Porphyry/src/components/portfolioPage/Topic.jsx
  - [x] Porphyry/src/components/portfolioPage/Portfolio.jsx
  - [x] Porphyry/src/components/portfolioPage/Viewpoint.jsx
  - [x] Porphyry/src/components/portfolioPage/SearchBar.jsx
  - [x] Porphyry/src/components/itemPage/TopicPath.jsx
  - [x] Porphyry/src/components/portfolioPage/GeographicMap.jsx
  - [x] Porphyry/src/components/itemPage/Attribute.jsx
- [X] Refactoring de l'évaluation de l'expression booléenne avec voll
- [ ] Retactoring de l'expression booléenne dans l'URI 
- [ ] Refactoring de la structure interne de l'expression booléenne

En fin de compte, seuls les deux premiers réusinages ont été nécessaires pour corriger le bug (le second aurait probablement été suffisant, mais le premier a permis une compréhension plus poussée du code des étudiants d'il y a deux ans et a donc facilité le second).
