### ISSUE TITLE
Use in your native language (at least French and English)

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#70]
### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation

**Comment by VanvanAlexandre** [comment]
Voici la maquette de l'issue
![57917002-36b78300-7894-11e9-834e-61d12cf48b58](https://user-images.githubusercontent.com/42775923/57919279-d119c580-7898-11e9-9132-6f230bd45b6a.png)

**Comment by benel** [comment]
Notez bien que la manière standard (selon le protocole HTTP) n'est pas celle-ci : elle utilise le mécanisme de _négociation de contenu_ (cf. LO10). Cette négociation va s'appuyer sur les paramètres du navigateur et plus spécialement sur la liste ordonnée des langues que comprend l'usager.

Autrement dit pour maquetter cette fonctionnalité vous devriez : 
- montrer une copie d'écran du paramétrage des langues dans un navigateur,
- montrer l'effet de ce paramètre sur l'interface.

Si vous travaillez sur les scénarios vous verrez qu'il faut à peu près 3 cas pour rendre compte de cette négociation.

**Comment by VanvanAlexandre** [comment]
Ceci est la parti de google chrome qui permet de modifier la langue native utilisé.
De plus quand on modifie la langue tout le body de porphyry se recharge.
![LanguageNavigator](https://user-images.githubusercontent.com/42775923/58320486-06379200-7e1c-11e9-83ff-dd975bbc7029.PNG)

**Comment by JoJoDU** [comment]
J'ai changé le button "nouveau point de vue" en utilisant language-js. 
J'introduis la pakage 'language-js' dans le fichier index.js. Ensuite, j'ajoute le dossier 'language' dessous le dossier 'public'. Et puis j'utilise la fonction t() dans le fichier 'ViewpointCreator.jsx'.

**Comment by benel** [comment]
Bonjour,
J'avais fait ce commentaire dans une autre discussion mais il y a eu une confusion sur le nom du package. J'avais parlé de `LinguiJS` et non `languageJS`.

1. Il est davantage adapté à à REACT (tout en étant compatible aussi avec du javascript classique).
2. Il permet de prendre comme "clefs" les textes originaux (plutôt que des codes).

**Comment by JoJoDU** [comment]
Bonjour,
J'ai trouvé que je ne peut pas installer le "LinguiJS". Je vois qu'il y a deux façon de l'installer.

> Follow setup guide either for projects using LinguiJS with Create React App or for general React projects.

J'ai éssayé la deuxième façon "for general React". Mais quand je checking l'installation en utilisant 'npm run extract', il y a une erreur qui me bloque.

**Comment by benel** [comment]
Bonjour,
@JoJoDU Votre message de 8h27 a été supprimé. Est-ce que cela signifie que vous n'êtes plus bloquée ?

**Comment by JoJoDU** [comment]
Bonjour,

Oui, je l’ai résolu. Merci.

**Comment by benel** [comment]
Rapport du Projet Mind qui a utilisé la même bibliothèque d'internationalisation : https://github.com/Hypertopic/LaSuli/wiki/Documentation-of-LaSuli-code-and-its-structure

**Comment by JoJoDU** [comment]
J'ai réussi de refaire en utilisant  le module "language-js". J'ai renouvellé dans notre branche Laguage.

**Comment by VanvanAlexandre** [comment]
Bonjour,

@benel, Nous avons terminé l'implémentation de ce ticket mais nous sommes confronté a un problème de conception.
Je m'explique, pour que language-js fonctionne il faut obligatoirement que la fonction Langage.init soit exécuté, et le meilleurs endroit que nous avons trouvé pour placer cette fonction est dans index.js avant le render pour que la fonction soit toujours lancer avant le rendu de la page soit envoyé.

Or si l'on recharge certaines pages, il semble que le render de index.js n'est pas exécuté, et par conséquent il y a une erreur js car le site ne parviens pas à trouver les traductions vu que la fonction Langage.init n'a pas été exécuté. 
Nous ne savons pas vraiment comme régler ce problème assez important, auriez-vous une piste de résolution ?
Dans l'attente de votre réponse.

**Comment by Damien71** [comment]
It would be interesting for our project "Studying abroad", that the UEs be available in French when they are UEs of foreign universities and that the UEs of the UTT be available in English for foreign students

**Comment by moonkeys** [comment]
Cette fonctionnalité pourrait être intéressante pour "Young Artist" car les dessins proviennent du monde entier. L'anglais étant la langue la plus répandue, cela faciliterait l'accès à la plateforme aux étrangers. De plus, la majorité des dessins ne viennent pas de France ce qui renforce l'intérêt d'une telle fonctionnalité.

**Comment by JosephNM** [comment]
For Greek vases project.
It can be interesting if the user works with people who don't speak the user native language. Although it seems to be not so necessary.

**Comment by sbramstein** [comment]
> For Greek vases project.
> It can be interesting if the user works with people who don't speak the user native language. Although it seems to be not so necessary.

In one hand this functionality would be intresting for the navigation since professionals from the whole world will use the platform. On the other hand most of the vases' descriptions will be in english or maybe in the archeologist's native language so it could be long if we would have to translate long paragraphs in various languages.

**Comment by benel** [comment]
> vases' descriptions 

@sbramstein @JosephNM Please note that this feature is just about the localization of the interface not of the data. It would be far far more complex and probably deceiving since such scientific terms meaning often depends on the speaker who uses them (esp. in Human sciences).

**Comment by ghost** [comment]
Pour "Collectives stories", ça serait intéressant de proposer la langue anglaise et française aux utilisateurs afin d'alimenter le catalogue d'histoires internationales. De plus, notre partie prenante est italienne, et donc je pense qu'elle apprécierait d'avoir accès au logiciel en anglais.

**Comment by ChloeChamaillard** [comment]
Projet Approche par compétences de la formation :
Intéressant de l'avoir en plusieurs langues pour les étudiants en échanges

**Comment by benel** [comment]
@ChloeChamaillard Pourquoi pas... Mais on est d'accord que nous parlons de la localisation de l'interface et non de la traduction des données ?

**Comment by lerideew** [comment]
![Web 1920 – 1](https://user-images.githubusercontent.com/58439748/80081475-45ea8a80-8553-11ea-954f-a1185db8ff52.png)


On aurait donc en élément de l'interface :
Pour la page d'accueil :
| Libellé en français | traduction en anglais |
| ------------------- | ----------------------- |
| Tous les items | All items |
| Se connecter | Log in |
| Se déconnecter | Log out |
| Points de vue | Viewpoints |
| Nouveau point de vue | New Viewpoint |

Pour la page de création d'un item :
| Libellé en français | traduction en anglais |
| ------------------- | ----------------------- |
| Retour à l'accueil | Back to Home |
| Description | Description |
| Attributs du document | Document Attributes |
| Ajouter un attribut et une valeur | Add an attribute and a value |
| attribut : valeur | attribute: value |
| Ajouter une rubrique | Add a topic |

Pour la page de création d'un point de vue :
| Libellé en français | traduction en anglais |
| ------------------- | ----------------------- |
| Création du point de vue | Create a viewpoint |
| Nom du point de vue | Viewpoint name |
| Modification du point de vue | Modify a viewpoint |

**Comment by benel** [comment]
@lerideew Pour les actions, peut-être plutôt choisir des **verbes à l'infinitif**.

C'est vrai que pour l'instant ils apparaissent directement dans l'interface, ce qui ne correspond pas à notre approche du "contenu avant tout" (à la Facebook). Mais à terme, on les trouvera dans des menus contextuels.

Exemple dans Facebook : 

<img width="257" alt="Capture d’écran 2020-05-14 à 08 47 14" src="https://user-images.githubusercontent.com/597307/81901891-891ea300-95bf-11ea-919b-53a00f055e0a.png">

**Comment by garnier5** [comment]
### Stratégie d'implémentation

**Quelle partie du code sera impactée (classes, méthodes) ?**
L'index sera le plus impacté, car il doit chargé les catalogues de traductions pour qu'ils soient disponibles dans les différentes classes du projet.
On aura alors à ajouter une balise 
`<I18nProvider i18n={i18n} language="en" catalogs={catalogList}>`
pour que la bibliothèque @lingui se charge de traduire les fichiers dans les autres classes du projet.
Dans les autres classes, l'objectif sera d'identifier les textes en français pour les remplacer par la fonction fourni par @lingui pour sélectionner la traduction équivalente à la langue choisie. 

**Y aura-t-il des difficultés d'un point de vue algorithmique ? Avez-vous des pistes pour les résoudre ?**
L'algorithmique n'est pas le plus difficile. 
Ce qui risque d'être le plus compliqué, c'est d'apprendre à utiliser la bibliothèque @lingui.

**Les données dont vous avez besoin sont-elles déjà chargées par la page ?** 
Oui et non. Les données traduites en français sont déjà disponible sur la page.
Pour ce qui est de la traduction en anglais, il faut l'écrire dans un fichier.
D'après ce qu'impose la bibliothèque @lingui, les traductions sont dans différents fichiers (un fichier .po par langue).
Les traductions se présenteront sous cette forme :
```
msgid "add_an_attribute_and_a_value"
msgstr "Add an attribute and a value"
```

`msgid` représente l'id que l'on peut trouver dans une balise `<Trans>` de la page.
`msgstr` est la traduction dans la langue choisie.

**Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ?**
Oui, @lingui pour la gestion des différents catalogues de traduction.

**Doit-on intégrer des services extérieurs (ex : cartographie) ? De quelles fonctionnalités en particulier aura-t-on besoin ? Est-ce que le service choisi les propose ou doit-on passer chez un concurrent ? Comment s'utilisent ces fonctionnalités ? avec quels paramètres ?**
Non.

**Comment by garnier5** [comment]
### Une liste plus exhaustive des traductions avec une approche "contenu avant tout"

**Pour la page d'un item**
| Actuel | Français | Anglais |
| ------------------- | ------------------- | ----------------------- |
| valeur | valeur | value |
| Retour à l'accueil | Retourner à l'accueil | Go back to home page |
| Description | Description | Description |
| Attributs du document | Attributs du document | Document attributes |
| Ajouter un attribut et une valeur | Ajouter un attribut et une valeur | Add an attribute and a value |
| attribut : valeur | attribut : valeur | attribute: value |
| Voulez-vous réellement que l\'item affiché ne soit plus décrit à l\'aide de cette rubrique ? | Voulez-vous réellement que l\'item affiché ne soit plus décrit à l\'aide de cette rubrique ? | Do you really want the displayed item to no longer be described using this topic? |
| Choisir une rubrique parent... | Choisir une rubrique parent... | Choose a parent topic... |
| Ajouter une rubrique... | Ajouter une rubrique... | Add a topic... |

**Pour la page d'un portfolio**

| Actuel | Français | Anglais |
| ------------------- | ------------------- | ----------------------- |
| Inclure | Inclure | Include |
| Exclure | Exclure | Exclude |
| Déselectionner | Déselectionner | Deselect |
| Ou | Ou | Or |
| Et | Et | And |
| Points de vue | Points de vue | Points of view |
| Rechercher... | Rechercher... | Search... |
| Tous les items | Tous les items | All items |
| Thème inconnu | Thème inconnu | Unknown topic |
| Nouveau point de vue | Nouveau point de vue | New point of view |


**Pour la page d'un point de vue**
| Actuel | Français | Anglais |
| ------------------- | ------------------- | ----------------------- |
| Retour à l'accueil | Retourner à l'accueil | Go back to home page |
| Nom du point de vue | Nom du point de vue | Viewpoint name |
| Modification du point de vue | Modifier un point de vue | Modify a viewpoint |
| Création du point de vue | Créer un point de vue | Create a viewpoint |

**Pour l'authentification**
| Actuel | Français | Anglais |
| ------------------- | ------------------- | ----------------------- |
| Se déconnecter | Se déconnecter | Log out |
| nom d'utilisateur | nom d'utilisateur | username |
| mot de passe | mot de passe | password |
| Se connecter | Se connecter | Log in |
| Se connecter... | Se connecter... | Log in... |

**Comment by garnier5** [comment]
Liste de sous-livrables imaginés pour la réalisation de ce ticket : 

- [x] Initialiser la bibliothèque @lingui dans index.js
- [x] Remplacer chaque texte dans le code par la fonction @lingui avec sa clé
- [x] Créer les fichiers d'associations clés/traduction dans chaque langue
- [x] Ajouter des boutons pour modifier la langue manuellement
- [ ] Voir si on peut utiliser la sélection automatique de langue proposé par les navigateurs

**Comment by benel** [comment]
>> Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ?

> Oui, @lingui pour la gestion des différents catalogues de traduction.

Je ne sais pas si vous avez vu, @garnier5 : le cas est un peu particulier, Lingui est à la fois une bibliothèque et un outil en ligne de commande. Vous avez un peu regardé ce qu'apportait l'outil ?

> D'après ce qu'impose la bibliothèque @lingui, les traductions sont dans différents fichiers (un fichier .po par langue).

Il y a plusieurs possibilités pour le format de référence des localisations... Avez-vous vu lesquelles ? Avec quels avantages et inconvénients ? Ce qui nous amènerait à choisir quelle solution ?

**Comment by benel** [comment]
@garnier5 Je n'avais pas vu que vous aviez déjà une demande d'intégration. Super !

Du coup, ce serait d'autant plus intéressant de documenter les choix que vous avez fait (dans le choix des formats, des identifiants)... Pour voir si ce sont des choix qui correspondent à une première implémentation ou si ce sont des choix pérennes qu'il est important de garder pour la suite du projet dans les années à venir.

**Comment by benel** [comment]
@garnier5 Concernant la traduction en anglais proprement dite, elle m'a l'air très bien.

Deux petits points d'attention cependant : 

- `Do you really want the displayed item to no longer be described using this topic?` me semble vraiment très compliqué... Et les anglais n'aiment pas les phrases compliquées...
- Il y a une petite hésitation dans vos traductions de `point(s) de vue`. Essayez d'homogéniser (en choisissant plutôt `viewpoint`, puisque c'est la traduction officielle, même si la connotation est effectivement un peu moins riche...).

**Comment by garnier5** [comment]
> Je ne sais pas si vous avez vu, @garnier5 : le cas est un peu particulier, Lingui est à la fois une bibliothèque et un outil en ligne de commande. Vous avez un peu regardé ce qu'apportait l'outil ?

On a choisi Lingui pour plusieurs raisons : déjà, il s'adapte plutôt bien avec React. Aussi, il se base sur un système de catalogues avec clé/valeur, et le choix de la clé est assez libre. Du coup, on peut prendre les textes initiales (actuellement dans le code) comme clé.

**Comment by garnier5** [comment]
> 
> 
> @garnier5 Je n'avais pas vu que vous aviez déjà une demande d'intégration. Super !

Ce n'est pas nous qui avons fait une demande d'intégration. Notre groupe se rapproche du résultat, mais nous n'avons pas encore terminé.

**Comment by benel** [comment]
> Du coup, on peut prendre les textes initiales (actuellement dans le code) comme clé.

Effectivement, j'aime bien ça, mais il faudrait expliciter pourquoi c'est intéressant.

**Comment by benel** [comment]
> Ce n'est pas nous qui avons fait une demande d'intégration. 

C'est moi qui ne suis pas précis, désolé. C'est un commit qui est apparu dans la discussion et non une PR.

**Comment by benel** [comment]
Je m'interroge aussi sur `Modify` (pour `modifier`)... Sur GitHub par exemple c'est plutôt "Edit"... Je ne sais pas comment c'est dit dans Facebook en anglais...

**Comment by Ciyax** [comment]
> 
> 
> Je m'interroge aussi sur `Modify` (pour `modifier`)... Sur GitHub par exemple c'est plutôt "Edit"... Je ne sais pas comment c'est dit dans Facebook en anglais...

Oui effectivement `Edit` est une traduction plus commune en général

**Comment by benel** [comment]
>> Je ne sais pas si vous avez vu, @garnier5 : le cas est un peu particulier, Lingui est à la fois une bibliothèque et un outil en ligne de commande. Vous avez un peu regardé ce qu'apportait l'outil ?

> On a choisi Lingui pour plusieurs raisons : déjà, il s'adapte plutôt bien avec React. Aussi, il se base sur un système de catalogues avec clé/valeur, et le choix de la clé est assez libre. Du coup, on peut prendre les textes initiales (actuellement dans le code) comme clé.

Dans cette question, je faisais plutôt référence au "[CLI](https://lingui.js.org/tutorials/cli.html)".

**Comment by Ciyax** [comment]
> 
> 
> > > Je ne sais pas si vous avez vu, @garnier5 : le cas est un peu particulier, Lingui est à la fois une bibliothèque et un outil en ligne de commande. Vous avez un peu regardé ce qu'apportait l'outil ?
> 
> > On a choisi Lingui pour plusieurs raisons : déjà, il s'adapte plutôt bien avec React. Aussi, il se base sur un système de catalogues avec clé/valeur, et le choix de la clé est assez libre. Du coup, on peut prendre les textes initiales (actuellement dans le code) comme clé.
> 
> Dans cette question, je faisais plutôt référence au "[CLI](https://lingui.js.org/tutorials/cli.html)".

L'avantage du CLI c'est qu'il nous permet de créer automatiquement la base de traduction. A partir du moment où la langue par défaut a été défini en français, tout fragment de texte (balisé avec `<Trans/>` ou `t`) dans le code sera automatiquement clé et valeur pour la langue française, et clé pour les autres langues ajoutées.

**Comment by garnier5** [comment]
> L'avantage du CLI c'est qu'il nous permet de créer automatiquement la base de traduction. A partir du moment où la langue par défaut a été défini en français, tout fragment de texte (balisé avec `<Trans/>` ou `t`) dans le code sera automatiquement clé et valeur pour la langue française, et clé pour les autres langues ajoutées.

Et aussi le fait que l'on va pouvoir utiliser le navigateur comme source de langue, plutôt que des boutons.

**Comment by Ciyax** [comment]
> 
> > D'après ce qu'impose la bibliothèque @lingui, les traductions sont dans différents fichiers (un fichier .po par langue).
> 
> Il y a plusieurs possibilités pour le format de référence des localisations... Avez-vous vu lesquelles ? Avec quels avantages et inconvénients ? Ce qui nous amènerait à choisir quelle solution ?

Oui il y a 3 possibilités de format, le .po (que nous utilisons), le .json et un format un peu plus brut défini originalement par LinguiJS mais basé sur .json

Le .json est fichier standard qui n'apporte pas plus d'intérêts que ça (seulement pour sa légèreté), là où le .po apporte des métadonnées : on sait où se trouve exactement le fragment de texte à traduire, si Lingui détecte des erreurs de traduction ou dans la forme, etc...

Qui plus est le .po n'est pas propre à LinguiJS, c'est un format de fichier défini par la boîte à outils GNU, et est alors utilisé par de nombreux outils de localisation. Ce qui veut dire que ce format de fichier peut être amené à être modifié/optimisé suivant les retours de la communauté

**Comment by lerideew** [comment]
Voici les scénarios qui ont été écrits pour ce ticket :

Scénario: Consulter le portfolio en anglais

Soit "vitraux" le portfolio ouvert
Quand un visiteur selectionne la langue "en"
Alors la page contient "Viewpoints"
Et la page contient "New viewpoint"
Et la page contient "All items"

Scénario: Consulter le portfolio en français

Soit "vitraux" le portfolio ouvert
Quand un visiteur selectionne la langue "fr"
Alors la page contient "Points de vue"
Et la page contient "Nouveau point de vue"
Et la page contient "Tous les items"

**Comment by lerideew** [comment]
Voici les ajouts fait dans les fichiers: 

event.rb

Quand ("un visiteur selectionne la langue {string}") do |language|
  click_on 'trad-'+ language
end

outcome.rb

Alors("Alors la page contient {string}") do |text|
  expect(page).to have_content text
end

**Comment by benel** [comment]
Il me semblait que vous étiez plutôt partis sur les choix de langue dans les préférences du navigateur...
Si c'est le cas, dans votre test, il faut que vous modifiiez les entêtes des requêtes HTTP...

On avait utilisé ça dans un autre projet:
```ruby
  page.driver.header 'Accept-Language', language
```

Où `language` peut être par exemple : 
- `'es'`
- `'fr'`
- `'en-US,en,fr`
- `'es;q=1.0,fr-FR;q=0.9,fr;q=0.8,en;q=0.7'`

**Comment by benel** [comment]
Du coup, si vous voulez tester l'internationalisation, il faut prévoir les différents cas : 

- le site possède la langue préférée,
- le site ne possède pas la langue préférée mais une des langues souhaitées,
- le site ne possède aucune des langues souhaitées.

**Comment by lerideew** [comment]
J'ai essayé d'utiliser page.driver.header 'Accept-Language', language.

Cependant j'ai cette erreur 
![image](https://user-images.githubusercontent.com/58439748/83127628-af256680-a0da-11ea-9875-47347c5449ec.png)

**Comment by benel** [comment]
> J'ai essayé d'utiliser page.driver.header 'Accept-Language', language.
> Cependant j'ai cette erreur

On utilise un driver de test différent que dans le vieux projet dont j'ai tiré mon exemple, il est donc effectivement possible que les paramètres soient légèrement différents. 

Voici la documentation de Cuprite (le driver que l'on utilise) : 

https://github.com/rubycdp/cuprite

**Comment by benel** [comment]
> J'ai essayé d'utiliser page.driver.header 'Accept-Language', language.
> Cependant j'ai cette erreur

@lerideew On utilise un driver de test différent de celui utilisé dans le vieux projet dont j'ai tiré mon exemple, il est donc effectivement possible que les paramètres soient légèrement différents. 

Voici la documentation de Cuprite (le driver que l'on utilise) : https://github.com/rubycdp/cuprite

La méthode porte effectivement un autre nom que `header`, vous avez trouvé lequel ?

**Comment by lerideew** [comment]
@benel 
Après avoir regardé la documentation de Cuprite dans laquelle la partie sur les entêtes HTTP mentionne deux possibilités et avoir testé les deux : 
page.driver.headers = { "Accept-Language" => language }
page.driver.add_headers("Accept-Language" => language)

(language étant la variable de type string, ici language est 'fr')

L'erreur suivante est affichée :

Soit la langue du navigateur est 'fr'             # features/step_definitions/context.rb:56
      Invalid parameters (Ferrum::BrowserError)
      ./features/step_definitions/context.rb:57:in `"la langue du navigateur est {string}"'
      features/lang_set.feature:7:in `Soit la langue du navigateur est 'fr''

**Comment by benel** [comment]
> Soit la langue du navigateur est **'fr'** # features/step_definitions/context.rb:56
Invalid parameters (Ferrum::BrowserError)
./features/step_definitions/context.rb:57:in "la langue du navigateur est {string}**"'** features/lang_set.feature:7:in Soit la langue du navigateur est **'fr''**

@lerideew Dans votre message d'erreur, il y a un mélange étrange d'apostrophes et de guillemets... Dans Cucumber, j'ai toujours utilisé des guillemets. Vous avez essayé avec des guillemets ?

**Comment by lerideew** [comment]
@benel J'ai essayé de mettre des guillemets mais rien ne change le message reste le même
Invalid parameters (Ferrum::BrowserError)
      ./features/step_definitions/context.rb:57:in `"la langue du navigateur est {string}"'
      features/portfolio_consult.feature:27:in `Soit la langue du navigateur est "fr"'

**Comment by benel** [comment]
> J'ai essayé de mettre des guillemets mais rien ne change le message reste le même

Juste avec des messages d'erreur c'est difficile de vous aider. J'aurais besoin de voir les extraits de code (l'appel de la fonction dans le fichier Cucumber et sa définition dans le fichier Capybara)...

**Comment by lerideew** [comment]
@benel 
Scénario: Consulter le portfolio en langue préférée

Soit la langue du navigateur est "fr"
Et "vitraux" le portfolio ouvert
Alors la page contient "Points de vue"
Et la page contient "Nouveau point de vue"
Et la page contient "Tous les items"


Soit("la langue du navigateur est {string}") do |language|
  page.driver.add_headers("Accept-Language" => language)
end

OU

Soit("la langue du navigateur est {string}") do |language|
  page.driver.headers = { "Accept-Language" => language }
end

**Comment by benel** [comment]
> Scénario: Consulter le portfolio en langue préférée

Attention à ne pas confondre `Fonctionnalité` et `Scénario` : il y a plusieurs scénarios par fonctionnalité comme autant de "cas".

> Soit("la langue du navigateur est {string}") do |language|
page.driver.add_headers("Accept-Language" => language)
end

Je ne vois pas où est l'erreur. Je vais essayer sur mon poste...

**Comment by benel** [comment]
Chez moi, ça passe très bien...
```
cucumber features/language.feature
# language: fr
Fonctionnalité: Consulter dans sa langue

  Scénario:                                    # features/language.feature:5
    Soit la langue du navigateur est "fr"      # features/step_definitions/context.rb:56
    Et "vitraux" le portfolio ouvert           # features/step_definitions/context.rb:12
    Alors la page contient "Points de vue"     # features/step_definitions/outcome.rb:43
    Et la page contient "Nouveau point de vue" # features/step_definitions/outcome.rb:43
    Et la page contient "Tous les items"       # features/step_definitions/outcome.rb:43

1 scenario (1 passed)
5 steps (5 passed)
0m1.337s
```

**Comment by benel** [comment]
Voici ce que j'ai testé : 

## features/language.feature
```cucumber
#language: fr

Fonctionnalité: Consulter dans sa langue

Scénario:

Soit la langue du navigateur est "fr"
Et "vitraux" le portfolio ouvert
Alors la page contient "Points de vue"
Et la page contient "Nouveau point de vue"
Et la page contient "Tous les items"
```

## features/step_definitions/context.rb

```ruby
Soit("la langue du navigateur est {string}") do |language|
  page.driver.add_headers("Accept-Language" => language)
end
```

## features/step_definitions/outcome.rb 

```ruby
lors("la page contient {string}") do |localization|
  expect(page).to have_content localization
end
```

**Comment by benel** [comment]
J'ai utilisé une version installée sur mon ordinateur (avec Ruby). 
Les messages d'erreur vous les avez obtenus comment ?
- sur le serveur d'intégration continue ?
- avec la version dockerisée ?
- avec une installation locale (en ruby) ?

**Comment by benel** [comment]
> avec la version dockerisée ?

Ah, effectivement, je viens de tester avec la version dockerisée et j'ai une erreur avec "ferrum" comme si le driver ne gérait pas cette option...

**Comment by garnier5** [comment]
> Ah, effectivement, je viens de tester avec la version dockerisée et j'ai une erreur avec "ferrum" comme si le driver ne gérait pas cette option...

C'était effectivement avec la version dockerisée...

**Comment by benel** [comment]
J'essaie de mettre à jour le conteneur au cas où ce serait un bug de cuprite corrigé depuis décembre..

**Comment by benel** [comment]
C'est le cas 🎉 
Je vais publier ma mise à jour du conteneur...

**Comment by garnier5** [comment]
J'ai essayé de mettre à jour l'image sur ma machine avec : 
```
docker pull benel/porphyry
docker pull benel/cucumber-capybara
```

Je lance avec : 
```
alias cucumber='docker run --rm --volume "$(pwd)":/app --tty --env APP_HOST="http://192.168.99.1:3000/" benel/cucumber-capybara'
cucumber features/lang_set.feature --retry 1
```

Mais aucun changement de mon côté. Et toi @lerideew ?

**Comment by benel** [comment]
> J'ai essayé de mettre à jour l'image sur ma machine avec :
> docker pull benel/cucumber-capybara

C'est bien cette commande, mais ce n'est pas encore prêt. Je suis en ADSL et le débit montant est très faible. Il reste environ 300 Mo à envoyer.

Vous pouvez voir la date des versions publiées ici : https://hub.docker.com/r/benel/cucumber-capybara/tags

Je vous préviens quand c'est fait.

**Comment by benel** [comment]
>  Il reste environ 300 Mo à envoyer.

Ça y est !

**Comment by garnier5** [comment]
Ça marche ! 🎉

**Comment by lerideew** [comment]
De mon coté aussi (désolé du manque de réponse, ma connexion Internet a fait des siennes) 🎉
