### ISSUE TITLE
Browse topics using tags cloud

### ISSUE THREAD

**Issue by CorentinLthr-old** [Hypertopic/Porphyry#80]
#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Mockups
- [ ] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

### Phase 3
- [ ] Screencast

**Comment by benel** [comment]
Porphyry v5 and v6 implement a multiple interactive tag cloud showing tags relations on mouse-over (described [here](http://publications.icd.utt.fr/ce329c153e7b8873a03ec02847008459)):

![cloud](https://raw.githubusercontent.com/wiki/Hypertopic/Protocol/porphyry_paestum_coupe.png)

If we want to implement the same in Porphyry v7 (which is Web-based), a nice way to do this could be with [D3.js](https://d3js.org).

**Comment by GuillaumeGilles42** [comment]
# task to do 

- [ ] scenario
- [ ] maquette
- [ ] recipe test
- [ ] implementation

**Comment by sab91** [comment]
# Task to do

- [ ] scenario ( @taher100  & @sab91 )
- [ ]  maquette ( @VictorKL @ @liyangsifei )
- [ ] recipe test
- [ ] implementation

**Comment by liyangsifei** [comment]
2 questions for the maquette :
1. In the fragment part of this view (right side), it shows only the fragment related to the sub-category selected or the item with the fragments colored?
2. What would be the title of the grey bar on the top of the fragment part and list of the item?

**Comment by liyangsifei** [comment]
<img width="1429" alt="56725472-33295400-674d-11e9-9438-17ba0afa1c82" src="https://user-images.githubusercontent.com/24189721/57858646-b93b3680-77f1-11e9-8f17-45e3981bb8c2.png">

**Comment by benel** [comment]
> What would be the title of the grey bar on the top of the fragment part and list of the item?

It is supposed to stay as it is: a list of corpora. Go and see @valentin-utt's mockup  in #48. Please note that could have created a mockup of just the page you had to design.

- [ ] You should also challenge your design with other members especially your icons. Which is a tag cloud and which is a hierarchy.
- [ ] Because the structure of your data is very simple (with only one viewpoint), we miss an important part of the design. It is not very clear if the buttons are for every viewpoint or not.
- [ ] What is exactly "David". This should mention viewpoints... Why is David so separated from its topics? Do coders really need to change a thin grey underline with a heavy border ?

**Comment by liyangsifei** [comment]
Mockup without category selected:
<img width="1429" alt="maquette_sans_select" src="https://user-images.githubusercontent.com/24189721/57920376-2951c700-789b-11e9-885b-b1cfc00041c0.png">

Mockup with the category 'Bonheur' selected:
<img width="1429" alt="maquette2_select" src="https://user-images.githubusercontent.com/24189721/57920370-25be4000-789b-11e9-9616-449c608419e6.png">

**Comment by liyangsifei** [comment]
mockups updated (icons and a new mockup presents the action of the switch button):
Mockup initial without any category selected:
<img width="1429" alt="maquette_sans_select" src="https://user-images.githubusercontent.com/24189721/58365145-45b7ba00-7ec0-11e9-8109-64e45ec6b278.png">

Category 'bonheur' selected:
<img width="1429" alt="maquette2_select" src="https://user-images.githubusercontent.com/24189721/58365140-3df81580-7ec0-11e9-9fe9-f8937d9525d6.png">

No category selected & when the button 'switch to mode category' clicked
<img width="1429" alt="maquette_switch_to_cat" src="https://user-images.githubusercontent.com/24189721/58365139-39cbf800-7ec0-11e9-9412-1b9e5e87884e.png">

**Comment by benel** [comment]
Pour vous aider à tester les styles CSS avec Capybara : 
https://medium.com/@TheSunwave/testing-your-css-styles-with-capybara-556022e0076d

**Comment by arnaud9145** [comment]
![Capture d’écran 2019-06-06 à 11 14 12](https://user-images.githubusercontent.com/1856194/59021524-418a8580-884c-11e9-898a-f71dd6ae0e1f.png)
Tag Cloud implementation v1 looks like that

**Comment by SorelMboua** [comment]
For the group "Greek Vases" I think this is relatively important. It could be useful for the user to be able to browse through categories using tags.

**Comment by paasshme** [comment]
Pour le projet "EUT+" nous pensons qu'il serait intéressant de consulter les mots les plus recherchés via un nuage de point, afin d'avoir une vue des tendances actuelles de recherche.

**Comment by benel** [comment]
> Pour le projet "EUT+" nous pensons qu'il serait intéressant de consulter les mots les plus recherchés via un nuage de point, afin d'avoir une vue des tendances actuelles de recherche.

@JacquesMironneau @Hypertopic/competences-eut Pourquoi pas, effectivement. Par contre, toujours pour être sûr que l'on parle de la même chose, on est d'accord que le nuage de catégories (et non de points ou de mots) est une visualisation alternative des données qui pour l'instant sont présentés uniquement sous forme d'une arborescence ?
Les catégories seraient donc "à plat", classées par ordre alphabétique, et leur taille correspondrait aux nombres qui apparaissent pour l'instant à droite des catégories.
